FROM cypress/base:10

# WORKDIR /app

COPY . .

RUN npm install

RUN $(npm bin)/cypress verify

# CMD [ "start-server-and-test", "start", "http://localhost:8081", "cy:run" ]  
CMD [ "npm", "run", "test:e2e:local"  ]